source:      .
destination: ./_site
includes:    ./_includes

permalink:   /:title.html

description: ""

rdiscount:
  extensions: []

defaults:
  -
    scope:
      path: ""
    values:
      ogtype: "website"
  -
    scope:
      path: ""
      type: "posts"
    values:
      ogtype: "article"
